HTTP/1.1 201 Created //501ms
Date: Fri, 11 Sep 2026 17:18:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 10
Connection: close
access-control-allow-credentials: true
etag: W/"a-OU6dZUlmoXw3mK0MSAaA6ruuo2o"
strict-transport-security: max-age=15552000; includeSubDomains
vary: Origin, Accept-Encoding
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-ratelimit-limit: 100
x-ratelimit-remaining: 99
x-ratelimit-reset: 1789147146
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
Server-Timing: cfCacheStatus;desc="DYNAMIC", cfEdge;dur=8,cfOrigin;dur=407
Report-To: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=lQs0O0UI7wX%2FGDgHXktp7TvSrGm4E0zFOnrqQ2nIJSh0qiQ%2Fn1egb%2FYKm91Mn3bqezRmWlDcBPeB39F0PDxkSbnwrDF8PgDpB1LXKJ0Bp9rBuk86iycwEnmMNq4oURgJ"}]}
Nel: {"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}
Server: cloudflare
CF-RAY: a39855a91a4b8033-PRG

{"id":195}